package com.example.offlinepasswordwallet.ui.screens

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.padding
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material3.Button
import androidx.compose.material3.Card
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Slider
import androidx.compose.material3.Switch
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableFloatStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.example.offlinepasswordwallet.di.ServiceLocator
import com.example.offlinepasswordwallet.password.PasswordGenerator
import com.example.offlinepasswordwallet.settings.AppSettings
import kotlin.math.roundToInt

/**
 * Reusable generator UI (§10–§15). A fresh password is generated immediately on
 * first show and on every relevant change; "Generate Again" re-rolls. If [onUse]
 * is non-null an "Use this password" action is shown (embedded-in-edit mode).
 */
@Composable
fun GeneratorPanel(
    onUse: ((String) -> Unit)?,
    modifier: Modifier = Modifier,
) {
    val settings by ServiceLocator.settingsRepository.settings
        .collectAsStateWithLifecycle(initialValue = AppSettings())

    var initialized by remember { mutableStateOf(false) }
    var length by remember { mutableFloatStateOf(PasswordGenerator.DEFAULT_LENGTH.toFloat()) }
    var useSpecial by remember { mutableStateOf(true) }
    var generated by remember { mutableStateOf("") }

    fun regen() {
        generated = PasswordGenerator.generate(length.roundToInt(), useSpecial)
    }

    // Seed defaults from settings once, then generate immediately.
    LaunchedEffect(settings) {
        if (!initialized) {
            length = settings.defaultPasswordLength
                .coerceIn(PasswordGenerator.MIN_LENGTH, PasswordGenerator.MAX_LENGTH).toFloat()
            useSpecial = settings.defaultUseSpecialChars
            initialized = true
            regen()
        }
    }

    Column(
        modifier = modifier.fillMaxWidth(),
        verticalArrangement = Arrangement.spacedBy(12.dp),
    ) {
        Card(Modifier.fillMaxWidth()) {
            Text(
                text = generated.ifEmpty { "…" },
                fontFamily = FontFamily.Monospace,
                style = MaterialTheme.typography.titleMedium,
                modifier = Modifier.padding(16.dp).testTag("generated_password"),
            )
        }

        Text("Password Length: ${length.roundToInt()}")
        Slider(
            value = length,
            onValueChange = { length = it; regen() },
            valueRange = PasswordGenerator.MIN_LENGTH.toFloat()..PasswordGenerator.MAX_LENGTH.toFloat(),
            steps = PasswordGenerator.MAX_LENGTH - PasswordGenerator.MIN_LENGTH - 1,
            modifier = Modifier.testTag("length_slider"),
        )

        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.SpaceBetween,
        ) {
            Text("Use special characters")
            Switch(
                checked = useSpecial,
                onCheckedChange = { useSpecial = it; regen() },
                modifier = Modifier.testTag("special_switch"),
            )
        }
        Text(
            "Allowed symbols: ${PasswordGenerator.SPECIAL}",
            style = MaterialTheme.typography.bodySmall,
        )

        OutlinedButton(
            onClick = { regen() },
            modifier = Modifier.fillMaxWidth().testTag("generate_again"),
        ) { Text("Generate Again") }

        if (onUse != null) {
            Button(
                onClick = { onUse(generated) },
                modifier = Modifier.fillMaxWidth().testTag("use_password"),
            ) { Text("Use this password") }
        }
    }
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun PasswordGeneratorScreen(onBack: () -> Unit, onUse: ((String) -> Unit)?) {
    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("Password generator") },
                navigationIcon = {
                    IconButton(onClick = onBack) {
                        Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Back")
                    }
                },
            )
        },
    ) { padding ->
        Column(Modifier.fillMaxSize().padding(padding).padding(16.dp)) {
            GeneratorPanel(onUse = onUse)
        }
    }
}
